name: calc_triangle
description: Flutter project calculating the sides in a right triangle

publish_to: "none"


version: 2.1.1+11

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3

  get: ^4.7.2

  logger: ^2.5.0
  #share: ^2.0.4
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.2
  sticky_headers: ^0.3.0

dependency_overrides:
  win32: ^5.1.1  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"
  flutter_native_splash: ^2.4.5
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:

    - assets/images/triangle/
    - assets/images/triangle/right/
    - assets/images/triangle/scalene/
    - assets/images/triangle/isosceles/
    - assets/images/triangle/equilateral/

  fonts:
    - family: montserrat
      fonts:
        - asset: fonts/montserrat_light.ttf
          weight: 300
        - asset: fonts/montserrat_regular.ttf
          weight: 400
        - asset: fonts/montserrat_medium.ttf
          weight: 500
        - asset: fonts/montserrat_semibold.ttf
          weight: 600
        - asset: fonts/montserrat_bold.ttf
          weight: 700
        - asset: fonts/montserrat_mediumitalic.ttf
          style: italic
 

 

# flutter pub get && dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#E0F2F1" # белый фон для адаптивной иконки
  adaptive_icon_foreground: "assets/icon/icon.png" # используем ту же иконку как передний план
  min_sdk_android: 21
  adaptive_icon_foreground_inset: 30 # отступ 20% от каждого края
  remove_alpha_channel_ios: true

flutter_native_splash:
  # Основные настройки
  color: "#102A27"  # Темный фон для splash screen
  image: "assets/icon/icon_a12.png"  # Иконка для splash
  
  # Отключаем для платформ, которые не используем
  android: true
  ios: false
  web: false

  # Полноэкранный режим
  fullscreen: true
  
  # Настройки для Android 12+
  android_12:
    image: "assets/icon/icon_a12.png"  # Специальная иконка для Android 12
    color: "#102A27"  # Цвет фона для Android 12+
    icon_background_color: "#E0F2F1"  # Цвет фона иконки (белый)
  
  # Настройка позиционирования изображения
  android_gravity: center



