name: Flutter Build APK

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decrypt .env file
        run: |
          mkdir -p $HOME/secrets
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.FILE_PASSPHRASE }}" \
          --output $HOME/secrets/.env .env.gpg

      - name: Decrypt keystore file
        run: |
          mkdir -p android/app
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.FILE_PASSPHRASE }}" \
          --output android/app/keystore.jks android/app/keystore.jks.gpg

      - name: Load environment variables
        run: |
          if [ -f "$HOME/secrets/.env" ]; then
            while IFS= read -r line || [ -n "$line" ]; do
              if [[ ! -z "$line" && ! "$line" =~ ^[[:space:]]*# ]]; then
                echo "$line" >> $GITHUB_ENV
              fi
            done < "$HOME/secrets/.env"
          else
            echo "Ошибка: Файл .env не найден!"
            exit 1
          fi

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk